---
# tasks file for apigee-opdk-setup-cassandra-registration
- name: Fail the role if we have not target response file
  assert:
    that:
      - target_response_file_path is defined
    msg: "Please provide the target_response_file_path"

- debug:
    var: target_response_file_path

- debug:
    var: local_apigee_secure_path

- pause:

- name: Copy target response file to control server
  fetch:
    src: "{{ target_response_file_path }}"
    dest: "{{ local_apigee_secure_path }}"
    flatten: true

- name: Copy target response file control server to management server
  copy:
    src: "{{ local_apigee_secure_path }}/{{ target_response_file_path | basename }}"
    dest: "{{ target_response_file_path }}"
  delegate_to: "{{ ms_ip }}"

- name: Setup component with target response file
  shell: "{{ apigee_service }} edge-management-server apigee-registration-setup -f {{ target_response_file_path }}"
  delegate_to: "{{ ms_ip }}"


